pipeline {
    agent{
            label 'ubuntu'
    }
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("sonar-scan"){
            steps {
                withSonarQubeEnv('sonarqube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Hossnia_geo'
                }
            }
        }
        stage("maven1"){
            steps {
                sh 'mvn clean validate compile test install test package'
            }
        }

    stage("upload artifact"){
        steps {
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd \
            -T target/bio*.jar \
            "http://ec2-35-175-130-147.compute-1.amazonaws.com:8081/artifactory/geolocation/051924/bio_${BUID_TAG}"'
        }
    }
    }
}
